### ISSUE TITLE
Command ":telescope fzf" doesn't work with NvChad under ArchLinux

### ISSUE THREAD

**Issue by basheewang** [nvim-telescope/telescope-fzf-native.nvim#112]
I checked the NvChad is shipped with telescope and telescope-fzf-native by default. The build is also success, and I can find the build/libfzf.so file existed. But when I try to run command "telescope fzf", I have below error msg:

![image](https://github.com/nvim-telescope/telescope-fzf-native.nvim/assets/5795648/fefe1a08-f0b5-4560-8586-6278454de0e6)

I have no idea what happened. Please kindly help on this.

**Comment by Conni2461** [comment]
telescope-fzf-native is not a normal extension (like others).

On load it replaces internal functions (sorter) by updating configs so that already provided sorters like `Telscope find_files` have fzf syntax.

It doesn't actually expose a new sorter. It enhances all pickers that already exist, builtin or extensions
