### ISSUE TITLE
Better windows support (makefile)

### ISSUE THREAD

**Issue by luisiacc** [nvim-telescope/telescope-fzf-native.nvim#24]
Got this error while compiling the plugin with `make`

```
mkdir -p build
cc -O3 -Wall -Werror -fpic -shared src/fzf.c -o build/libfzf.so
process_begin: CreateProcess(NULL, cc -O3 -Wall -Werror -fpic -shared src/fzf.c -o build/libfzf.so, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:8: build/libfzf.so] Error 2
```

make version:
```
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

As you can see, I'm on Windows 10.
Same error on powershell, cmd and alacritty.

- Tried with version 3.81 of `make`, same error.

**Comment by luisiacc** [comment]
So, I found out that this its because it is not recognizing `cc` as a command, changing it for 'gcc' makes it work. What is `cc` ?

**Comment by Conni2461** [comment]
On default `$(CC) = cc` and `cc` links to gcc. Thats the default usually for any unix based system.
![image](https://user-images.githubusercontent.com/15233006/121798395-4f86f400-cc26-11eb-9fc0-c2836a75f88b.png)

I have to admit, windows is not really supported by me because i don't use it or have any windows knowledge. But i will definitely address this at some point, maybe with a CI job. Thanks for bringing it on my table.

**Comment by luisiacc** [comment]
Since you are considering windows, `mkdir -p build` on windows creates 2 folders `-p` and `build`, I know, weird.

**Comment by Conni2461** [comment]
On linux `mkdir` throws an error without `-p` :rofl: 

```
       -p, --parents
              no error if existing, make parent directories as needed
```

I'll look into all this. Thanks for telling me
