### ISSUE TITLE
E5108: Error executing lua ...escope-fzf-native.nvim/lua/telescope/_extensions/fzf.lua:115: attempt to index local 'opts' (a nil value)

### ISSUE THREAD

**Issue by AllenDang** [nvim-telescope/telescope-fzf-native.nvim#33]
This error is triggered by `Telescope lsp_dynamic_workspace_symbols`.

E5108: Error executing lua ...escope-fzf-native.nvim/lua/telescope/_extensions/fzf.lua:115: attempt to index local 'opts' (a nil value)

**Comment by Conni2461** [comment]
Yeah i run into this a couple of times now. The actual problem is that `lsp_dynamic_workspace_symbols` isn't passing on opts to sorter. https://github.com/nvim-telescope/telescope.nvim/commit/253d3aaa6b43eac6b11341b325e34d37dc459af3#r54580667
I still fixed it here for now because i can see future picker implementation also not respecting this.

Thanks for reporting :)
