### ISSUE TITLE
use fzf option --no-sort

### ISSUE THREAD

**Issue by Frydac** [nvim-telescope/telescope-fzf-native.nvim#42]
Hi,

when using this fzf extension, is it possible to specify the fzf option '--no-sort' in some way for a specific telescope picker.

e.g. I would love to have the --no-sort option for this mapping with the MRU/oldfiles
(for example: I can usually see in the list what I want, and start typing something that matches, but then it starts sorting in a way that the result I want is much later in the list (I like to have a long list of oldfiles just in case :))):
`vim.api.nvim_set_keymap('n', '<leader>;', '<cmd>lua require("telescope.builtin").oldfiles()<cr>', {})`

**Comment by Conni2461** [comment]
no this is currently not supported and is out of score for this repo. `fzf-native` only does the calculation of the score and telescope core does the sorting based on this score. `fzf-native` is a reimplementation of fzf scoring algorithm in c with lua bindings.

But we are currently working on implementing something like this in core.
You should track these issues and the PR: https://github.com/nvim-telescope/telescope.nvim/issues/939 https://github.com/nvim-telescope/telescope.nvim/issues/1080 https://github.com/nvim-telescope/telescope.nvim/pull/1401

I would close this because its not possible here
